### ISSUE TITLE
KakaoTalk.login success 콜백 함수가 실행되지 않습니다.

### ISSUE THREAD

**Issue by javanreal** [taejaehan/Cordova-Kakaotalk-Plugin#9]
iOS에서 로그인을 실행하면 로그인 팝업이 뜨고 정상적으로 로그인이 되지만,
콜백 함수를 실행하지 않는 현상이 발생하고 있습니다.
fail이 된 경우 콜백 함수는 정상적으로 실행됩니다.

혹여 같은 오류가 발생하거나, 해결책을 알고 계신 분 없나요?

**Comment by maeumop** [comment]
저도 같은 현상을 격고 있는데, 문제의 원인을 전혀 모르겠습니다.
